import differential_topological_aspects_diffeomorphisms_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace differential_topological_aspects_diffeomorphisms_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end differential_topological_aspects_diffeomorphisms_theorem_canonical_lane_mathlib
end HautevilleHouse
